# Generated by Django 3.2.5 on 2021-09-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knnpredict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=10)),
                ('account', models.CharField(default='example@gmail.com', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('height', models.CharField(default='', max_length=20)),
                ('weight', models.CharField(default='', max_length=20)),
                ('sexual', models.CharField(default='', max_length=100)),
                ('birth_date', models.CharField(default='', max_length=100)),
                ('contactor', models.CharField(default='', max_length=100)),
                ('contactor_phone', models.CharField(default=9999999999, max_length=100)),
            ],
            options={
                'db_table': 'user_data_model',
            },
        ),
    ]
